/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppSensitivityRouteImport } from './routes/_app/sensitivity'
import { Route as AppScenariosRouteImport } from './routes/_app/scenarios'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppMonthlyRouteImport } from './routes/_app/monthly'
import { Route as AppFinancingRouteImport } from './routes/_app/financing'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSensitivityRoute = AppSensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthlyRoute = AppMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancingRoute = AppFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/budget': typeof AppBudgetRoute
  '/financing': typeof AppFinancingRoute
  '/monthly': typeof AppMonthlyRoute
  '/results': typeof AppResultsRoute
  '/scenarios': typeof AppScenariosRoute
  '/sensitivity': typeof AppSensitivityRoute
  '/statements': typeof AppStatementsRoute
}
export interface FileRoutesByTo {
  '/budget': typeof AppBudgetRoute
  '/financing': typeof AppFinancingRoute
  '/monthly': typeof AppMonthlyRoute
  '/results': typeof AppResultsRoute
  '/scenarios': typeof AppScenariosRoute
  '/sensitivity': typeof AppSensitivityRoute
  '/statements': typeof AppStatementsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/budget': typeof AppBudgetRoute
  '/_app/financing': typeof AppFinancingRoute
  '/_app/monthly': typeof AppMonthlyRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/scenarios': typeof AppScenariosRoute
  '/_app/sensitivity': typeof AppSensitivityRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/financing'
    | '/monthly'
    | '/results'
    | '/scenarios'
    | '/sensitivity'
    | '/statements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/budget'
    | '/financing'
    | '/monthly'
    | '/results'
    | '/scenarios'
    | '/sensitivity'
    | '/statements'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/budget'
    | '/_app/financing'
    | '/_app/monthly'
    | '/_app/results'
    | '/_app/scenarios'
    | '/_app/sensitivity'
    | '/_app/statements'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitivity': {
      id: '/_app/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof AppSensitivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios': {
      id: '/_app/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monthly': {
      id: '/_app/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof AppMonthlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financing': {
      id: '/_app/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof AppFinancingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppFinancingRoute: typeof AppFinancingRoute
  AppMonthlyRoute: typeof AppMonthlyRoute
  AppResultsRoute: typeof AppResultsRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSensitivityRoute: typeof AppSensitivityRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppFinancingRoute: AppFinancingRoute,
  AppMonthlyRoute: AppMonthlyRoute,
  AppResultsRoute: AppResultsRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSensitivityRoute: AppSensitivityRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
